version: '3'
services:
  protonmail-bridge:
    build:
      context: .
      args:
        PROTONMAIL_BRIDGE_VERSION:
        SMTP_PORT:
        IMAP_PORT:
    environment:
      BRIDGE_EXTRA_ARGS:
      PROTONMAIL_LOGIN:
      PROTONMAIL_PASSWORD:
      PROTONMAIL_EXTRA_2FA:
      SMTP_PORT:
      IMAP_PORT:
    ports:
      - "127.0.0.1:${SMTP_PORT}:${SMTP_PORT}"
      - "127.0.0.1:${IMAP_PORT}:${IMAP_PORT}"
