version: '3.3'
services:
  protonmail-bridge:
    volumes:
      - /home/stefan/docker/protonmail/:/home/protonmail/
    build:
      context: .
      args:
        PROTONMAIL_BRIDGE_VERSION:
        SMTP_PORT:
        IMAP_PORT:
    environment:
      BRIDGE_EXTRA_ARGS:
      BRIDGE_SPLIT_ADDRESS_MODE:
      PROTONMAIL_LOGIN:
      PROTONMAIL_PASSWORD:
      PROTONMAIL_EXTRA_2FA:
      SMTP_PORT:
      IMAP_PORT:
    ports:
      - "192.168.2.254:${SMTP_PORT}:${SMTP_PORT}"
      - "192.168.2.254:${IMAP_PORT}:${IMAP_PORT}"
